# Generated by Django 3.1.2 on 2020-10-05 14:11

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='English Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled')], max_length=2, verbose_name='Order Status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=50, verbose_name='English Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ar', models.TextField(verbose_name='Arabic Description')),
                ('description_en', models.TextField(verbose_name='English Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('main_image', models.ImageField(upload_to='products', verbose_name='Main Image')),
                ('slider', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='products'), size=None, verbose_name='Slider')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Price')),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None, verbose_name='Available Colors')),
                ('dimensions', models.CharField(max_length=30, verbose_name='Dimensions')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductOnSeasonalDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasonal_discounts', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Product On Seasonal Discount',
                'verbose_name_plural': 'Products On Seasonal Discount',
            },
        ),
        migrations.CreateModel(
            name='SeasonalDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='English Name')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Period')),
                ('global_discount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('products', models.ManyToManyField(through='ecommerce.ProductOnSeasonalDiscount', to='ecommerce.Product')),
            ],
            options={
                'verbose_name': 'Seasonal Discount',
                'verbose_name_plural': 'Seasonal Discounts',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Stars')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='ecommerce.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.AddField(
            model_name='productonseasonaldiscount',
            name='seasonal_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.seasonaldiscount'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('on_discount', models.BooleanField(default=False, verbose_name='On Discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lines', to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_lines', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='ecommerce.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorites', to='ecommerce.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorites', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fees', to='accounts.region')),
            ],
            options={
                'verbose_name': 'Delivery Fee',
                'verbose_name_plural': 'Delivery Fees',
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lines', to='ecommerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart_lines', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Cart Line',
                'verbose_name_plural': 'Cart Lines',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=50, verbose_name='English Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_categories', to='ecommerce.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
                'unique_together': {('name', 'category')},
            },
        ),
    ]
