# Generated by Django 3.1.2 on 2020-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20201022_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered')], default='P', max_length=2, verbose_name='Order Status'),
        ),
    ]
