# Generated by Django 3.1.2 on 2020-11-10 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20201109_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slider',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
