# Generated by Django 3.1.2 on 2021-01-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20201110_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card1_visibility', models.BooleanField(default=True, verbose_name='Visibility')),
                ('card1_header', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header')),
                ('card1_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('card1_content', models.CharField(blank=True, max_length=150, null=True, verbose_name='Content Text')),
                ('card1_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Button Text')),
                ('card1_image', models.ImageField(blank=True, null=True, upload_to='index', verbose_name='Image')),
                ('section1_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('section1_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Content Text')),
                ('section2_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('section2_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Content Text')),
                ('section2_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Button Text')),
                ('section2_image', models.ImageField(blank=True, null=True, upload_to='index', verbose_name='Image')),
                ('section3_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('section3_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Content Text')),
                ('section3_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Button Text')),
                ('section4_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('section4_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Content Text')),
                ('section4_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Button Text')),
                ('section4_image1', models.ImageField(blank=True, null=True, upload_to='index', verbose_name='Image 1')),
                ('section4_image2', models.ImageField(blank=True, null=True, upload_to='index', verbose_name='Image 2')),
                ('section5_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('section5_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Content Text')),
                ('section5_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Button Text')),
                ('section1_categories', models.ManyToManyField(related_name='index_cats', to='ecommerce.Category', verbose_name='Display Categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
