# Generated by Django 3.1.2 on 2021-01-17 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0009_indexcontent_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned')], default='P', max_length=2, verbose_name='Order Status'),
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('P', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned')], max_length=2, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('P', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned')], max_length=2, verbose_name='New Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_changes', to='ecommerce.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
