# Generated by Django 3.1.2 on 2021-01-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_visible'),
        ('ecommerce', '0012_auto_20210120_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('weight_threshold', models.PositiveIntegerField(blank=True, default=0, verbose_name='Weight Threshold')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='deliveryfee',
            name='region',
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fees', to='accounts.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Fee'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Free Delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryfee',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned'), ('RE', 'Refund'), ('PA', 'Paid')], default='P', max_length=2, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='new_status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned'), ('RE', 'Refund'), ('PA', 'Paid')], max_length=2, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='previous_status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned'), ('RE', 'Refund'), ('PA', 'Paid')], max_length=2, verbose_name='Previous Status'),
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fees', to='ecommerce.deliverycompany'),
            preserve_default=False,
        ),
    ]
