# Generated by Django 3.1.2 on 2021-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20210121_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcontent',
            name='card1_content',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section1_text',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section2_text',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section3_text',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section4_text',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section5_text',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
    ]
