# Generated by Django 3.1.5 on 2021-01-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210123_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'verbose_name': 'Product On Seasonal Discount', 'verbose_name_plural': 'Products On Seasonal Discount'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.CreateModel(
            name='DeliveryGuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_guys', to='ecommerce.deliverycompany')),
            ],
            options={
                'verbose_name': 'Delivery Guy',
                'verbose_name_plural': 'Delivery Guys',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('delivery_guys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.deliveryguy', verbose_name='Delivery Guy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ecommerce.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
