# Generated by Django 3.1.2 on 2021-02-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20210128_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'verbose_name': 'Delivery Company', 'verbose_name_plural': 'Delivery Companies'},
        ),
    ]
