# Generated by Django 3.1.2 on 2021-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20210201_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycompany',
            name='base_fee',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Base Fee'),
        ),
    ]
