# Generated by Django 3.1.2 on 2021-02-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_deliverycompany_base_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='visible',
        ),
    ]
