# Generated by Django 3.1.2 on 2021-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_remove_orderline_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reference'),
        ),
    ]
