# Generated by Django 3.1.2 on 2021-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_auto_20210204_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='stars',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Stars'),
        ),
    ]
