# Generated by Django 3.1.2 on 2021-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20210218_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
