# Generated by Django 3.1.2 on 2021-02-27 10:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_deliveries_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcontent',
            name='assistance_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Assistance Number'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None, verbose_name='Available Colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Arabic Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='English Name'),
        ),
    ]
