# Generated by Django 3.1.2 on 2021-02-27 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0026_auto_20210227_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('complaint', models.CharField(choices=[('DP', 'Delivery Problem'), ('PP', 'Product Problem'), ('SP', 'Service Problem'), ('O', 'Other')], max_length=2, verbose_name='Complaint')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('treated', models.BooleanField(blank=True, default=False, verbose_name='Treated')),
                ('against', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints', to='ecommerce.deliveryguy', verbose_name='Against')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints', to='ecommerce.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
