# Generated by Django 3.1.5 on 2021-03-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_auto_20210317_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartline',
            name='visible',
        ),
    ]
