# Generated by Django 3.1.5 on 2021-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_auto_20210424_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcontent',
            name='Instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned'), ('RE', 'Refund'), ('DE', 'Delayed'), ('PA', 'Paid'), ('NA', 'No Answer')], default='P', max_length=2, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='new_status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned'), ('RE', 'Refund'), ('DE', 'Delayed'), ('PA', 'Paid'), ('NA', 'No Answer')], max_length=2, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='previous_status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('R', 'Returned'), ('RE', 'Refund'), ('DE', 'Delayed'), ('PA', 'Paid'), ('NA', 'No Answer')], max_length=2, verbose_name='Previous Status'),
        ),
    ]
