# Generated by Django 3.1.5 on 2021-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_auto_20210425_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcontent',
            name='Instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.twitter.com', verbose_name='Twitter'),
        ),
    ]
