# Generated by Django 3.1.5 on 2021-05-25 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210204_1606'),
        ('ecommerce', '0037_auto_20210522_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='accounts.profile'),
        ),
    ]
