# Generated by Django 3.1.5 on 2021-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_auto_20210525_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcontent',
            name='card1_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='section2_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='section3_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='section4_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='section5_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
    ]
