# Generated by Django 3.1.5 on 2021-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20210526_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
            },
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='base_fee',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Fee per 1kg'),
        ),
    ]
