# Generated by Django 3.1.5 on 2021-06-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_auto_20210530_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcontent',
            name='pintrest',
            field=models.URLField(blank=True, default='https://www.pintrest.com', verbose_name='Pintrest'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='tumblr',
            field=models.URLField(blank=True, default='https://www.tumblr.com', verbose_name='Tumblr'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='youtube',
            field=models.URLField(blank=True, default='https://www.youtube.com', verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ai',
            field=models.CharField(blank=True, default='sdfqsdfqsdfqsdfqsdf', max_length=255, verbose_name='AI'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='nif',
            field=models.CharField(blank=True, default='sdfqsdfqsdfqsdfqsdf', max_length=255, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rc',
            field=models.CharField(blank=True, default='sdfqsdfqsdfqsdfqsdf', max_length=255, verbose_name='RC'),
        ),
    ]
