# Generated by Django 3.1.5 on 2021-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_auto_20210606_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='settings',
            name='assistance_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assistance Email'),
        ),
        migrations.AddField(
            model_name='settings',
            name='assistance_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assistance Number'),
        ),
    ]
