# Generated by Django 3.1.5 on 2021-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_auto_20210608_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Weight'),
        ),
    ]
