# Generated by Django 3.1.5 on 2021-07-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_auto_20210625_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Discount %')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='ExpiryDate')),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ecommerce.coupon', verbose_name='Applied Coupon'),
        ),
    ]
