# Generated by Django 3.1.5 on 2021-07-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_auto_20210728_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_usages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Usages'),
        ),
    ]
