# Generated by Django 3.1.5 on 2021-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_coupon_max_usages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_product',
            field=models.BooleanField(default=False, verbose_name='Free Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('DC', 'Delivery Canceled'), ('R', 'Returned'), ('RE', 'Refund'), ('DE', 'Delayed'), ('PA', 'Paid'), ('NA', 'No Answer')], default='P', max_length=2, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='new_status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('DC', 'Delivery Canceled'), ('R', 'Returned'), ('RE', 'Refund'), ('DE', 'Delayed'), ('PA', 'Paid'), ('NA', 'No Answer')], max_length=2, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='previous_status',
            field=models.CharField(choices=[('P', 'Pending'), ('RC', 'RECALL'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('OD', 'On Delivery'), ('D', 'Delivered'), ('DC', 'Delivery Canceled'), ('R', 'Returned'), ('RE', 'Refund'), ('DE', 'Delayed'), ('PA', 'Paid'), ('NA', 'No Answer')], max_length=2, verbose_name='Previous Status'),
        ),
    ]
