# Generated by Django 3.1.2 on 2020-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201007_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
