# Generated by Django 3.1.2 on 2021-02-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.region', verbose_name='Region'),
        ),
    ]
