# Generated by Django 3.1.2 on 2021-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210201_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'Client'), ('S', 'Staff'), ('A', 'Admin'), ('CA', 'Caller')], help_text="The user's type can be one of the available choices, Client, Staff or Admin.", max_length=2, verbose_name='Type'),
        ),
    ]
